//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contratado.
        /// </summary>
        internal static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración.
        /// </summary>
        internal static string AdministrationHeader {
            get {
                return ResourceManager.GetString("AdministrationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AppLogo {
            get {
                object obj = ResourceManager.GetObject("AppLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Avatar_1 {
            get {
                object obj = ResourceManager.GetObject("Avatar_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Avatar_2 {
            get {
                object obj = ResourceManager.GetObject("Avatar_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Avatar_3 {
            get {
                object obj = ResourceManager.GetObject("Avatar_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Avatar_4 {
            get {
                object obj = ResourceManager.GetObject("Avatar_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Avatar_5 {
            get {
                object obj = ResourceManager.GetObject("Avatar_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Avatar_6 {
            get {
                object obj = ResourceManager.GetObject("Avatar_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Avatar_7 {
            get {
                object obj = ResourceManager.GetObject("Avatar_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Avatar_8 {
            get {
                object obj = ResourceManager.GetObject("Avatar_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo es obligatorio.
        /// </summary>
        internal static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        internal static string HomeHeader {
            get {
                return ResourceManager.GetString("HomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario desconocido o contraseña equivocada.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesión iniciada. Bienvenido {0}.
        /// </summary>
        internal static string LoginWelcomeFormat {
            get {
                return ResourceManager.GetString("LoginWelcomeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha cerrado su sesión.
        /// </summary>
        internal static string LogoutNotification {
            get {
                return ResourceManager.GetString("LogoutNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que quiere cerrar la sesión?.
        /// </summary>
        internal static string LogoutPromptContent {
            get {
                return ResourceManager.GetString("LogoutPromptContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        internal static string LogoutPromptTitle {
            get {
                return ResourceManager.GetString("LogoutPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazado.
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que quiere rechazar esta solicitud?.
        /// </summary>
        internal static string RequestRejectPromptContent {
            get {
                return ResourceManager.GetString("RequestRejectPromptContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar solicitud.
        /// </summary>
        internal static string RequestRejectPromptTitle {
            get {
                return ResourceManager.GetString("RequestRejectPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitudes.
        /// </summary>
        internal static string RequestsHeader {
            get {
                return ResourceManager.GetString("RequestsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialista.
        /// </summary>
        internal static string Specialist {
            get {
                return ResourceManager.GetString("Specialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación se ha ejecutado con éxito.
        /// </summary>
        internal static string SuccessfullyAddedElement {
            get {
                return ResourceManager.GetString("SuccessfullyAddedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formulario se ha almacenado con éxito.
        /// </summary>
        internal static string SuccessfullyAddedRequest {
            get {
                return ResourceManager.GetString("SuccessfullyAddedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación se ha ejecutado con éxito.
        /// </summary>
        internal static string SuccessfullyRemoveElement {
            get {
                return ResourceManager.GetString("SuccessfullyRemoveElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación se ha ejecutado con éxito.
        /// </summary>
        internal static string SuccessfullyUpdatedElement {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro que quieres eliminar esta entidad?.
        /// </summary>
        internal static string SureToRemoveElement {
            get {
                return ResourceManager.GetString("SureToRemoveElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshacer.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre una edad válida.
        /// </summary>
        internal static string ValidAge {
            get {
                return ResourceManager.GetString("ValidAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Cuidado!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error.
        /// </summary>
        internal static string WorkplaceAssignedError {
            get {
                return ResourceManager.GetString("WorkplaceAssignedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha asignado la plaza y se ha archivado la solicitud.
        /// </summary>
        internal static string WorkplaceAssignedNotification {
            get {
                return ResourceManager.GetString("WorkplaceAssignedNotification", resourceCulture);
            }
        }
    }
}
